title: Longlong Li's Homepage
page-top-title: Longlong Li
top-section-bg-text: Graph Neural Networks · Topological Deep Learning · AI for Science
home-subtitle: Longlong Li &ensp;|&ensp; 李 龙龙
copyright-text: '&copy; Longlong Li 2025. All Rights Reserved.'
