title: Longlong Li's Homepage
page-top-title: Longlong Li
home-subtitle: Longlong Li &ensp;|&ensp; 李龙龙
copyright-text: '&copy; Longlong Li 2025. All Rights Reserved.'
home-md: "contents/home.md"
publications-md: "contents/publications.md"
awards-md: "contents/awards.md"
funds-md: "contents/funds.md"
talks-md: "contents/talks.md"
